# Generated by Django 6.0.3 on 2026-03-11 16:05

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.attachment_upload_path, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригінальна назва')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME-тип')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Розмір (байти)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено о')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ticket', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Завантажено')),
            ],
            options={
                'verbose_name': 'Вкладення',
                'verbose_name_plural': 'Вкладення',
                'ordering': ['created_at'],
            },
        ),
    ]
